-- ============================================================
-- Baby Journey — Conteúdo semanal do desenvolvimento do bebê
-- Semanas 1-42
-- ============================================================

INSERT INTO public.baby_development_content
  (week, fruit_name, fruit_emoji, size_cm, weight_g, development_summary, organ_development, mom_changes, common_symptoms, recommended_food, important_care, curiosities)
VALUES
(1,  'Semente de Papoula', '🌱', 0.1, 0.0,
 'A fertilização aconteceu. O zigoto se divide rapidamente em células que formarão todos os tecidos do seu bebê.',
 'Divisão celular intensa. As células-tronco se diferenciam em três camadas: ectoderma, mesoderma e endoderma.',
 'O corpo começa a produzir hCG — o hormônio da gravidez. Você pode não sentir nada ainda.',
 ARRAY['Nenhum ainda'],
 'Ácido fólico é essencial agora. Consuma folhas verdes, feijão e suplementos.',
 'Agende uma consulta pré-natal assim que confirmar a gravidez.',
 'O sexo do bebê já está definido desde a fertilização pelo cromossomo X ou Y do espermatozoide.'),

(2,  'Semente de Gergelim', '🌿', 0.2, 0.0,
 'O embrião se implanta no útero. Começa a formação do saco amniótico.',
 'A placenta começa a se formar. O tubo neural inicia o desenvolvimento.',
 'O nível de hCG aumenta. Pode haver leve sangramento de implantação.',
 ARRAY['Leve cólica', 'Sensibilidade nos seios'],
 'Continue com ácido fólico. Evite álcool, cigarro e medicamentos sem prescrição.',
 'Evite saunas, banheiras quentes e atividades de alto impacto.',
 'O coração do bebê começa a se formar nesta semana!'),

(3,  'Semente de Chia', '🫘', 0.3, 0.0,
 'O embrião tem três camadas de células que formarão todos os órgãos e sistemas do corpo.',
 'O sistema nervoso central começa a se desenvolver a partir do tubo neural.',
 'O útero começa a aumentar. Pode haver sensação de inchaço.',
 ARRAY['Fadiga', 'Náusea leve', 'Aumento da frequência urinária'],
 'Proteínas magras, grãos integrais e muita água.',
 'Comece a evitar peixes com alto teor de mercúrio (atum, peixe-espada).',
 'O embrião está 10.000 vezes maior do que no momento da fertilização!'),

(4,  'Semente de Papoula', '🌸', 0.4, 0.0,
 'O coração primitivo começa a bater! O embrião tem a aparência de um pequeno disco.',
 'Os primeiros batimentos cardíacos acontecem. O encéfalo começa a se dividir.',
 'A menstruação está atrasada — hora de fazer o teste!',
 ARRAY['Náusea', 'Cansaço', 'Seios doloridos', 'Mudanças de humor'],
 'Ácido fólico, ferro, cálcio. Frango, ovos, leite, feijão.',
 'Faça o teste de gravidez e agende a primeira consulta.',
 'O coração do bebê bate cerca de 160 vezes por minuto — quase o dobro do adulto!'),

(5,  'Semente de Gergelim', '🫘', 0.6, 0.0,
 'O embrião começa a parecer com um girino. As primeiras estruturas do rosto aparecem.',
 'O cérebro se divide em cinco partes. O coração tem quatro câmaras em desenvolvimento.',
 'Enjoo matinal pode começar. O útero do tamanho de uma laranja.',
 ARRAY['Náusea intensa', 'Vômitos', 'Hipersensibilidade olfativa', 'Sonolência'],
 'Gengibre ajuda com náuseas. Biscoito de água e sal, frutas, proteínas leves.',
 'Evite cheiros fortes. Coma pouco e com frequência para controlar a náusea.',
 'O olfato da mamãe fica hipersensível por causa do aumento de estrogênio.'),

(6,  'Lentilha', '🫘', 0.8, 0.0,
 'O rosto toma forma: olhos, nariz e boca começam a aparecer. As mãozinhas são visíveis.',
 'O coração já tem quatro câmaras. O fígado, os rins e os pulmões estão se desenvolvendo.',
 'O útero dobrou de tamanho. A cintura pode começar a alagar.',
 ARRAY['Náusea', 'Fadiga extrema', 'Maior sensibilidade emocional', 'Salivação excessiva'],
 'Vitamina B6 ajuda com náuseas. Iogurte, queijo, nozes.',
 'Descanse bastante. O corpo trabalha muito para criar a placenta.',
 'O bebê já tem impressões digitais únicas formando-se nas pontinhas dos dedos.'),

(7,  'Mirtilo', '🫐', 1.3, 0.0,
 'O bebê tem o tamanho de um mirtilo. Os órgãos principais estão se formando rapidamente.',
 'Os rins começam a funcionar. O cérebro cresce 100 neurônios por minuto.',
 'O volume de sangue aumenta. Veias podem ficar mais visíveis.',
 ARRAY['Náusea e vômito', 'Dores de cabeça', 'Constipação', 'Mudanças de humor'],
 'Vitamina C (laranja, acerola), ácido fólico, ferro.',
 'Evite banhos muito quentes. Beba muita água. Consulte seu médico sobre suplementos.',
 'O cérebro do bebê cresce mais rápido nesta fase do que em qualquer outro período da vida.'),

(8,  'Framboesa', '🍓', 1.6, 1.0,
 'Todos os órgãos principais existem agora, embora ainda imaturos. Os movimentos começam.',
 'Os ossos começam a endurecer. Os pulmões se ramificam. O rosto está mais definido.',
 'O útero do tamanho de um grapefruit. Possível ganho de peso de 0,5-1kg.',
 ARRAY['Náusea', 'Azia', 'Frequência urinária', 'Seios maiores e doloridos'],
 'Cálcio (leite, brócolis, sardinha), proteínas, ferro.',
 'Primeiro ultrassom geralmente acontece entre 8-12 semanas. Agende!',
 'O bebê já pode fazer movimentos, mas você não os sente ainda.'),

(9,  'Azeitona', '🫒', 2.3, 2.0,
 'O embrião agora é chamado de feto. Todos os órgãos essenciais estão presentes.',
 'Os músculos se desenvolvem. O bebê pode engolir. Os dentes de leite se formam.',
 'O aumento dos seios é notável. O cansaço ainda é intenso.',
 ARRAY['Fadiga', 'Enjoo', 'Constipação', 'Dores lombares leves'],
 'Fibras (frutas, legumes), proteínas, ômega-3 (peixe, linhaça).',
 'Durma de lado com um travesseiro entre os joelhos para conforto.',
 'O feto já tem reflexos: se você tocar o útero, ele se afasta.'),

(10, 'Ameixa Seca', '🫒', 3.1, 4.0,
 'O bebê é agora definitivamente um feto. Os órgãos genitais começam a se diferenciar.',
 'O cérebro cresce rapidamente. As unhas dos dedos começam a aparecer.',
 'O risco de aborto espontâneo cai significativamente após esta semana.',
 ARRAY['Náusea diminuindo', 'Azia', 'Pressão pélvica'],
 'Continue com ácido fólico. Adicione vitamina D (sol, peixe).',
 'O exame de Translucência Nucal (TN) é feito entre 11-14 semanas.',
 'O bebê pode ser visto se movendo no ultrassom, embora você ainda não sinta.'),

(11, 'Lima', '🍋', 4.1, 7.0,
 'O bebê está quase totalmente formado. Começa a urinar e engolir líquido amniótico.',
 'Os dentes de leite estão em desenvolvimento. O diafragma se forma — o bebê pode soluçar!',
 'O útero sobe para o abdômen. O enjoo pode começar a diminuir.',
 ARRAY['Náusea diminuindo', 'Azia', 'Ronco', 'Varizes leves'],
 'Ferro (carne vermelha magra, espinafre), vitamina C para absorção do ferro.',
 'Use protetor solar — manchas de pele são comuns durante a gravidez.',
 'O bebê já tem impressões digitais completamente formadas.'),

(12, 'Limão', '🍋', 5.4, 14.0,
 'Fim do 1º trimestre! O bebê está completamente formado. O risco de problemas cai muito.',
 'Os reflexos estão presentes. O bebê abre e fecha os punhos. Esboça sorrisos.',
 'A náusea começa a melhorar para muitas mamães. Energia retornando.',
 ARRAY['Azia', 'Constipação', 'Dores de cabeça', 'Tonturas leves'],
 'Aumentar calorias em ~300 kcal/dia. Fibras, proteínas, cálcio.',
 'Informe seu dentista sobre a gravidez — cuidados bucais são importantes.',
 'O bebê já tem todos os 20 dentes de leite formados dentro da gengiva.'),

(13, 'Damasco', '🍑', 7.4, 23.0,
 'Início do 2º trimestre! O bebê está crescendo rapidamente. As feições estão mais definidas.',
 'Os ossos endurecem. O pâncreas produz insulina. Os rins filtram o sangue.',
 'A "barriguinha" começa a aparecer. Pele mais radiante para muitas.',
 ARRAY['Energia aumentando', 'Azia', 'Dores abdominais leves (ligamentos)'],
 'Proteínas, cálcio, ferro, ômega-3. Aumente a ingestão de líquidos.',
 'Comece a usar creme para estrias preventivamente.',
 'O bebê já distingue luz e escuridão, mesmo que os olhos ainda estejam fechados.'),

(14, 'Pêssego', '🍑', 8.7, 43.0,
 'O bebê faz expressões faciais: caretas, sorrisos e franzidas de testa!',
 'A glândula tireoide produz hormônios. Os rins produzem urina. O pelo (lanugo) cobre o corpo.',
 'O útero cresce 1cm por semana agora. A cintura desaparece.',
 ARRAY['Sangramento gengival', 'Congestão nasal', 'Apetite aumentado'],
 'Vitamina A (cenoura, batata-doce), vitamina C, cálcio.',
 'Comece a dormir de lado (preferencialmente esquerdo) — melhora a circulação.',
 'O bebê tem sobrancelhas e cílios formando-se.'),

(15, 'Maçã', '🍎', 10.1, 70.0,
 'O bebê pode sugar o polegar! Os ossos ficam cada vez mais sólidos.',
 'O couro cabeludo toma forma. O esqueleto é visível no ultrassom.',
 'Muitas mamães sentem os primeiros movimentos (flutters) nesta semana.',
 ARRAY['Dores nas costas', 'Congestão', 'Gengivas inflamadas', 'Aumento de apetite'],
 'Cálcio, vitamina D, proteínas magras.',
 'Consulte sobre vacinação: gripe e dTpa são recomendadas na gravidez.',
 'O bebê pode ouvir sons do mundo externo pela primeira vez!'),

(16, 'Abacate', '🥑', 11.6, 100.0,
 'O bebê tem 100g! Movimentos ficam mais frequentes. Pode soluçar.',
 'Gordura subcutânea começa a se formar. O sistema circulatório está funcionando bem.',
 'A barriga é claramente visível. Possível dor no ligamento redondo.',
 ARRAY['Dores lombares', 'Manchas de pele', 'Inchaço leve nos pés'],
 'Ômega-3 (sardinha, salmão), vitamina E (azeite, amêndoas).',
 'Faça exercícios leves como caminhada e natação — com liberação médica.',
 'O bebê pode reagir a luzes brilhantes apontadas para o abdômen.'),

(17, 'Nabo', '🥔', 13.0, 140.0,
 'O bebê tem reflexos de sucção e deglutição mais desenvolvidos.',
 'O tecido adiposo se forma. O esqueleto passa de cartilagem para osso.',
 'O útero cresce rapidamente. Pode sentir os movimentos como "borboletas".',
 ARRAY['Dores nas costas', 'Azia intensa', 'Inchaço', 'Varizes'],
 'Ferro, proteínas, fibras. Evite frituras para reduzir a azia.',
 'Use travesseiro de suporte para gestantes ao dormir.',
 'O bebê está desenvolvendo a camada de mielina no sistema nervoso.'),

(18, 'Pimentão', '🫑', 14.2, 190.0,
 'O bebê ouve claramente! Pode reagir a músicas e voz dos pais.',
 'Os genitais estão completamente formados. Possível ver no ultrassom morfológico.',
 'Possível dor no nervo ciático. O "glow" da gravidez é real!',
 ARRAY['Dor ciática', 'Câimbras', 'Congestão nasal', 'Tonturas'],
 'Vitaminas do complexo B, magnésio (para câimbras), cálcio.',
 'Morfológico do 2º trimestre é feito entre 20-24 semanas. Agende!',
 'O bebê pode ouvir sua voz — fale, cante e leia para ele!'),

(19, 'Manga', '🥭', 15.3, 240.0,
 'O bebê está muito ativo! Os movimentos ficam mais fortes e perceptíveis.',
 'O vernix caseoso (substância branca protetora) cobre o corpo.',
 'Você definitivamente sente os chutes agora! Dor de azia pode ser intensa.',
 ARRAY['Azia', 'Dores lombares', 'Inchaço', 'Dificuldade de dormir'],
 'Alimentos ricos em fibra, probióticos, muito líquido.',
 'Comece o plano de parto. Pesquise sobre maternidades.',
 'Os dentes permanentes do bebê já estão se formando por trás dos dentes de leite.'),

(20, 'Banana', '🍌', 16.4, 300.0,
 'Metade da gravidez! O bebê engole líquido amniótico e pratica a digestão.',
 'As sobrancelhas e cílios estão completos. As unhas chegam às pontas dos dedos.',
 'Morfológico do 2º trimestre. Possível descobrir o sexo!',
 ARRAY['Azia', 'Dores na virilha', 'Falta de ar leve', 'Sonhos vívidos'],
 'Mantenha uma dieta balanceada. Aumento de 300-500 kcal/dia.',
 'Realize o exame morfológico do 2º trimestre. É o mais completo.',
 'O bebê está totalmente coberto de lanugo, pelos finos que o mantêm aquecido.'),

(21, 'Cenoura', '🥕', 26.7, 360.0,
 'O bebê dorme e acorda em ciclos regulares. Pode sonhar!',
 'Os pulmões se desenvolvem mais. O sistema digestivo matura gradualmente.',
 'O útero chega ao nível do umbigo. Possíveis câimbras nas pernas à noite.',
 ARRAY['Câimbras noturnas', 'Azia', 'Dores nos pés', 'Insônia leve'],
 'Cálcio e magnésio para câimbras. Hidratação adequada.',
 'Faça aulas de preparação para o parto. Pesquise sobre amamentação.',
 'O bebê tem ciclos de sono de 20-30 minutos — parecidos com os do recém-nascido.'),

(22, 'Papaia', '🍈', 27.8, 430.0,
 'O bebê tem sobrancelhas e cílios completamente formados. Abre os olhos ocasionalmente.',
 'O sistema imunológico começa a se desenvolver. As papilas gustativas estão maduras.',
 'O fundo do útero está 2-3 cm acima do umbigo. Refluxo pode piorar.',
 ARRAY['Azia intensa', 'Dores nas costas', 'Inchaço', 'Pressão pélvica'],
 'Refeições menores e mais frequentes para o refluxo.',
 'Faça o exame de glicemia gestacional (teste oral de tolerância à glicose).',
 'O bebê pode saborear o que a mamãe come através do líquido amniótico!'),

(23, 'Manga Grande', '🥭', 28.9, 501.0,
 'O bebê reage a sons externos com movimentos. Os pulmões produzem surfactante.',
 'O sangue está sendo produzido pela medula óssea. As articulações se movem suavemente.',
 'Possível aparecimento de linha nigra (linha escura no abdômen).',
 ARRAY['Dores lombares', 'Cãibras', 'Inchaço nos tornozelos', 'Dificuldade respiratória leve'],
 'Vitamina D, cálcio, ferro. Evite sódio para reduzir o inchaço.',
 'Comece a massagear o períneo para prepará-lo para o parto.',
 'As impressões digitais do bebê são únicas — diferentes até de gêmeos idênticos.'),

(24, 'Espiga de Milho', '🌽', 30.0, 600.0,
 'O bebê reage ao toque! Se você empurrar suavemente, ele pode empurrar de volta.',
 'Os pulmões continuam amadurecendo. O cérebro cresce significativamente.',
 'O útero chega 4cm acima do umbigo. Possível dor no nervo ciático.',
 ARRAY['Dor ciática', 'Inchaço', 'Azia', 'Falta de ar ao deitar'],
 'Magnésio, proteínas, ômega-3 para desenvolvimento cerebral.',
 'Faça o teste de glicemia se ainda não fez. Monitore a pressão arterial.',
 'A partir desta semana, bebês prematuros têm chances de sobrevivência com cuidados intensivos.'),

(25, 'Nabo Branco', '🌰', 34.6, 660.0,
 'O bebê tem gordura acumulando sob a pele. A pele vai ficando menos translúcida.',
 'O nariz começa a funcionar — o bebê pratica "respirar" líquido amniótico.',
 'Início do 3º trimestre se aproxima. Cansaço pode voltar.',
 ARRAY['Dores nas costas', 'Pressão pélvica', 'Falta de ar', 'Inchaço'],
 'Continue com ômega-3. Vitamina K (folhas verdes). Cálcio.',
 'Comece a contar os movimentos fetais diariamente.',
 'O bebê tem padrões de sono com movimentos oculares rápidos (sono REM) — pode sonhar!'),

(26, 'Alface Americana', '🥬', 35.6, 760.0,
 'Os olhos estão totalmente formados e o bebê pode piscar. Reage à luz.',
 'O cérebro se dobra e ganham sulcos (como um adulto). Pulmões quase maduros.',
 'Dor nas costelas pode aparecer. A barriga fica bem evidente.',
 ARRAY['Dor nas costelas', 'Insônia', 'Azia', 'Síndrome das pernas inquietas'],
 'Refeições menores à noite. Evite cafeína. Vitaminas do complexo B.',
 'Discuta o plano de parto com seu médico.',
 'O bebê pisca 20-25 vezes por minuto — o mesmo ritmo de um adulto acordado.'),

(27, 'Couve-flor', '🥦', 36.6, 875.0,
 'O bebê dorme 90% do tempo, preparando-se para os desafios do nascimento.',
 'O tecido cerebral se expande rapidamente. O sistema imunológico recebe anticorpos.',
 'Início do 3º trimestre! Contrações de Braxton-Hicks podem aparecer.',
 ARRAY['Contrações falsas (Braxton-Hicks)', 'Falta de ar', 'Frequência urinária', 'Dores nas costas'],
 'Proteínas, ferro, cálcio. Hidratação extra.',
 'Aprenda a distinguir contrações falsas das verdadeiras.',
 'O bebê reconhece a voz da mamãe e reage a ela — já é o som favorito dele!'),

(28, 'Pêssego Grande', '🍑', 37.6, 1005.0,
 'Início do 3º trimestre. O bebê abre e fecha os olhos. Os pulmões estão quase prontos.',
 'A gordura continua a acumular. O cérebro se dobra mais. Os olhos podem ser azuis.',
 'A barriga pode interferir no sono. Síndrome das pernas inquietas é comum.',
 ARRAY['Dificuldade para dormir', 'Azia severa', 'Inchaço', 'Dores nas costas'],
 'Ferro, cálcio, ômega-3. Evite deitar após comer.',
 'Faça o exame de estreptococo B (GBS) entre 35-37 semanas.',
 'O bebê pode ver luz filtrada pelo abdômen e reage piscando.'),

(29, 'Abóbora Butternut', '🎃', 38.6, 1153.0,
 'O bebê está mais ativo à noite. Pode empurrar com força os pés contra o útero.',
 'O cérebro e sistema nervoso completam o desenvolvimento básico.',
 'Falta de ar piora. O bebê "desce" nas próximas semanas.',
 ARRAY['Falta de ar', 'Azia', 'Inchaço severo', 'Pressão pélvica'],
 'Refeições pequenas e frequentes. Elevar levemente a cabeça ao dormir.',
 'Verifique a posição do bebê com seu médico.',
 'O bebê é capaz de sonhar com REM completo, como um adulto.'),

(30, 'Repolho', '🥬', 39.9, 1319.0,
 'O bebê sorteia de acordo com sons familiares. Pode virar para a posição cefálica.',
 'A medula óssea é a principal fonte de produção de glóbulos vermelhos.',
 'A barriga está bem grande. O bebê "cai" — alívio na respiração mas pressão na bexiga.',
 ARRAY['Pressão na bexiga', 'Contrações Braxton-Hicks mais fortes', 'Varizes', 'Hemorroidas'],
 'Continue com ferro e cálcio. Fibras para intestino.',
 'Prepare a mala da maternidade.',
 'O bebê recebe anticorpos da mamãe que o protegerão por meses após o nascimento.'),

(31, 'Coco', '🥥', 41.1, 1502.0,
 'O bebê é altamente reativo a estímulos externos. Os pulmões continuam amadurecendo.',
 'O cérebro cresce muito rápido. O bebê acumula gordura subcutânea.',
 'Cansaço extremo retorna. Dificuldade de posição ao dormir.',
 ARRAY['Insônia', 'Dores lombares severas', 'Inchaço extremidades', 'Falta de ar'],
 'Proteínas, ferro, cálcio. Evite sódio para controlar o inchaço.',
 'Monitore pressão arterial — pré-eclâmpsia pode se desenvolver.',
 'O bebê processa informações sensoriais: tato, audição, visão, paladar e cheiro.'),

(32, 'Jicama', '🧅', 42.4, 1702.0,
 'Os ossos estão totalmente formados, mas macios para facilitar o parto.',
 'O diâmetro da cabeça cresce 9,5mm por semana. As unhas chegam à ponta dos dedos.',
 'Visitas médicas aumentam para quinzenais.',
 ARRAY['Dificuldade de respirar', 'Insônia', 'Dores pélvicas', 'Inchaço'],
 'Vitamina C, ferro, cálcio. Hidratação essencial.',
 'Pesquise sobre os sinais de trabalho de parto.',
 'O bebê passa 90-95% do tempo dormindo dentro do útero.'),

(33, 'Abacaxi Pequeno', '🍍', 43.7, 1918.0,
 'O bebê detecta luz e escuridão e regula seu próprio ritmo circadiano.',
 'Os pulmões estão quase completamente maduros. Os ossos do crânio não estão fundidos.',
 'As contrações de Braxton-Hicks aumentam em frequência e intensidade.',
 ARRAY['Contrações frequentes', 'Pressão na pelve', 'Dificuldade ao caminhar', 'Azia'],
 'Datas (fruta) podem ajudar a preparar o colo do útero para o parto.',
 'Aprenda os sinais do trabalho de parto verdadeiro.',
 'O bebê já consegue coordenar a sucção, deglutição e respiração.'),

(34, 'Melão Cantalupo', '🍈', 45.0, 2146.0,
 'O bebê está praticamente formado! Ganho de peso é intenso agora.',
 'O lanugo começa a desaparecer. O vernix caseoso protege a pele.',
 'A "descida" do bebê alivia a falta de ar mas aumenta a pressão pélvica.',
 ARRAY['Pressão pélvica intensa', 'Hemorroidas', 'Inchaço', 'Insônia'],
 'Continue a alimentação equilibrada. Evite alimentos pesados à noite.',
 'Faça o exame GBS (estreptococo B) — importante para o plano do parto.',
 'O bebê pratica a respiração por 30-40 minutos por dia no líquido amniótico.'),

(35, 'Nabo Grande', '🥔', 46.2, 2383.0,
 'O bebê está com 35 semanas! Os rins estão funcionando completamente.',
 'O sistema nervoso central está quase completo. A gordura representa 15% do peso.',
 'A maioria dos órgãos internos está madura. Bebê seria viável se nascesse agora.',
 ARRAY['Frequência urinária extrema', 'Contrações', 'Dificuldade de caminhar', 'Fadiga'],
 'Proteínas, cálcio, vitamina D. Repouso necessário.',
 'Exame GBS entre 35-37 semanas se ainda não fez.',
 'Os bebês nascidos na semana 35 geralmente não precisam de UTI neonatal.'),

(36, 'Alface Romana', '🥗', 47.4, 2622.0,
 'O bebê está quase pronto! Está descendo para a posição de parto.',
 'A gordura no rosto torna as bochechas arredondadas. Os rins estão completamente maduros.',
 'Visitas semanais com o médico. Pode sentir que o bebê "caiu".',
 ARRAY['Pressão pélvica extrema', 'Dificuldade de dormir', 'Contrações de Braxton-Hicks', 'Descarga'],
 'Tâmaras, framboesas vermelhas (chá). Mantenha-se ativa com caminhadas leves.',
 'Finalize a mala da maternidade. Confirme o hospital.',
 'O bebê perdeu a maior parte do lanugo e está coberto de vernix caseoso.'),

(37, 'Acelga', '🥬', 48.6, 2859.0,
 'Bebê a termo! A gravidez chegou ao período de termo precoce.',
 'O cérebro ainda cresce (cresce 35% do nascimento aos 3 anos). Pulmões totalmente maduros.',
 'Tampão mucoso pode sair. Contrações podem ser mais regulares.',
 ARRAY['Contrações irregulares', 'Pressão pélvica', 'Perda do tampão', 'Descidas de humor'],
 'Hidratação, refeições leves. Datas podem ajudar.',
 'Saiba quando ir à maternidade: contrações 5-1-1 (5min intervalo, 1min duração, 1hora).',
 'O bebê nascido nesta semana é considerado de "termo precoce" — a maioria é saudável.'),

(38, 'Alho-poró', '🧅', 49.8, 3083.0,
 'O bebê está totalmente pronto! O sistema digestivo tem mecônio (primeiro cocô).',
 'O sistema imunológico ainda está se desenvolvendo. Os pulmões são totalmente maduros.',
 'Pode sentir contrações mais regulares. O colo do útero começa a dilatar.',
 ARRAY['Contrações regulares', 'Pressão pélvica intensa', 'Instinto do ninho', 'Diarreia leve'],
 'Refeições leves e de fácil digestão. Hidratação essencial.',
 'Identifique a diferença entre contrações verdadeiras e falsas.',
 'O bebê já reconhece seu nome e reage a ele!'),

(39, 'Melancia Pequena', '🍉', 50.7, 3288.0,
 'O bebê está a ponto! O nível de gordura está alto para regular a temperatura.',
 'Os anticorpos da mamãe protegem o bebê por meses. A pele está macia e enrugada.',
 'A qualquer momento! Sinais de trabalho de parto podem aparecer.',
 ARRAY['Contrações regulares', 'Ruptura membranas possível', 'Pressão extrema', 'Ansiedade'],
 'Alimentos leves. Beba muita água.',
 'Saiba os sinais de urgência: sangramento, fluido claro/verde, movimentos diminuídos.',
 'O bebê tem 300 ossos (recém-nascido), mais que um adulto que tem 206.'),

(40, 'Abóbora Pequena', '🎃', 51.2, 3462.0,
 'Data provável do parto! Apenas 5% dos bebês nascem exatamente na DPP.',
 'Tudo está pronto. O bebê pode nascer a qualquer momento.',
 'Paciência! Qualquer dia pode ser o grande dia.',
 ARRAY['Contrações', 'Ansiedade', 'Entusiasmo', 'Instinto do ninho intenso'],
 'Alimentos leves e energéticos. Castanhas, frutas.',
 'Monitore os movimentos fetais. Vá à maternidade se contrações 5-1-1 ou bolsa rompeu.',
 'Bebês "passados do prazo" até 42 semanas são geralmente saudáveis!'),

(41, 'Abóbora Média', '🎃', 51.7, 3597.0,
 'Bebê pós-termo. O médico pode discutir indução. Tudo bem, é comum.',
 'As unhas podem ser bem longas. A pele pode estar descamando.',
 'Monitoramento fetal intensivo. Possível indução do parto.',
 ARRAY['Desconforto', 'Ansiedade', 'Contrações'],
 'Tâmaras, caminhadas, sexo (com liberação médica) podem ajudar a induzir naturalmente.',
 'Monitoramento fetal 2x por semana é recomendado após 40 semanas.',
 'Apenas 5% dos bebês nascem na DPP — a maioria nasce entre 37-42 semanas.'),

(42, 'Abóbora Moranga', '🎃', 51.7, 3685.0,
 'Limite máximo da gravidez. A indução será indicada pelo médico.',
 'O bebê está saudável mas a placenta começa a envelhecer.',
 'Indução do parto será realizada. Seja qual for a forma, você está quase lá!',
 ARRAY['Desconforto intenso', 'Ansiedade', 'Exaustão'],
 'Refeições leves. Descanse ao máximo.',
 'Siga as orientações médicas. A indução é segura e necessária após 42 semanas.',
 'Você chegou ao fim da jornada! Em breve seu bebê estará nos seus braços. 💛');
