-- =============================================================
-- Baby Journey — Catálogo Mestre v2 (~350 itens)
-- Idempotente: ON CONFLICT (item_name, category) DO UPDATE
-- =============================================================
-- Colunas: category, subcategory, item_name, description,
--   ideal_quantity, max_quantity, need_level, criticality,
--   usage_period, buy_week_from, buy_week_to,
--   use_from_week, use_to_week,
--   can_borrow, can_rent, can_wait, good_as_gift,
--   is_large_item, weight_kg,
--   price_brl_min, price_brl_max, price_usd_min, price_usd_max,
--   avg_price_brl, avg_price_usd,
--   country_rec, base_recommendation,
--   tags, is_active, sort_order

-- Garantir constraint de unicidade para idempotência
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'layette_catalog_name_category_unique'
  ) THEN
    ALTER TABLE public.layette_catalog
      ADD CONSTRAINT layette_catalog_name_category_unique UNIQUE (item_name, category);
  END IF;
END $$;

INSERT INTO public.layette_catalog
  (category, subcategory, item_name, description,
   ideal_quantity, max_quantity, need_level, criticality,
   usage_period, buy_week_from, buy_week_to,
   use_from_week, use_to_week,
   can_borrow, can_rent, can_wait, good_as_gift,
   is_large_item, weight_kg,
   price_brl_min, price_brl_max, price_usd_min, price_usd_max,
   avg_price_brl, avg_price_usd,
   country_rec, base_recommendation,
   tags, is_active, sort_order)
VALUES

-- =============================================================
-- QUARTO (sort 1000+)
-- =============================================================
('quarto','Mobília','Berço Padrão',
 'Berço com grades reguláveis, certificação INMETRO',
 1,1,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,104,
 true,true,false,true,true,12,
 800,2500,150,500,1650,325,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['sono','quarto','essencial'],true,1010),

('quarto','Mobília','Berço Portátil (Moisés)',
 'Berço leve e portátil para os primeiros meses',
 1,1,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,36,0,16,
 true,true,false,true,false,4,
 200,600,40,120,400,80,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['sono','quarto','portátil'],true,1020),

('quarto','Mobília','Mini Berço / Bedside Sleeper',
 'Berço que se acopla à cama dos pais para co-sleeping seguro',
 1,1,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,36,0,26,
 true,true,false,true,false,6,
 400,1200,80,250,800,165,'usa','AGUARDAR_EUA',
 ARRAY['sono','co-sleeping','quarto'],true,1030),

('quarto','Mobília','Colchão para Berço',
 'Colchão firme, impermeável, certificação anti-sufocamento',
 1,1,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,104,
 false,false,false,true,false,3,
 200,600,40,120,400,80,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['sono','segurança'],true,1040),

('quarto','Mobília','Cômoda com Trocador',
 'Cômoda com trocador integrado e gavetas organizadoras',
 1,1,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,208,
 false,true,false,true,true,30,
 600,2000,120,400,1300,260,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['higiene','quarto'],true,1050),

('quarto','Mobília','Poltrona de Amamentação',
 'Poltrona reclinável com apoio lateral para amamentação',
 1,1,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,34,0,208,
 true,true,false,true,true,30,
 500,2000,100,400,1250,250,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['amamentação','quarto'],true,1060),

('quarto','Eletrodoméstico','Babá Eletrônica com Vídeo',
 'Monitor com câmera, sensor de temperatura e visão noturna',
 1,1,'recomendado','IMPORTANTE','NO_NASCIMENTO',24,36,0,208,
 false,false,true,true,false,1,
 300,1000,40,180,650,110,'usa','AGUARDAR_EUA',
 ARRAY['segurança','monitoramento'],true,1070),

('quarto','Eletrodoméstico','Umidificador de Ar',
 'Umidificador ultrassônico para manter umidade entre 50-70%',
 1,1,'recomendado','IMPORTANTE','NO_NASCIMENTO',24,36,0,208,
 false,false,true,false,false,2,
 150,400,30,80,275,55,'usa','AGUARDAR_EUA',
 ARRAY['saúde','quarto','ar'],true,1080),

('quarto','Decoração','Móbile Musical',
 'Móbile com luzes, músicas e rotação automática para berço',
 1,1,'conveniente','OPCIONAL','NO_NASCIMENTO',24,36,0,26,
 true,false,true,true,false,1,
 80,300,15,60,190,37,'usa','AGUARDAR_EUA',
 ARRAY['desenvolvimento','quarto'],true,1090),

('quarto','Eletrodoméstico','Projetor de Estrelas',
 'Projetor com sons da natureza e luzes coloridas para dormir',
 1,1,'conveniente','OPCIONAL','NO_NASCIMENTO',24,36,0,104,
 true,false,true,true,false,1,
 80,250,15,40,165,27,'usa','AGUARDAR_EUA',
 ARRAY['sono','quarto'],true,1100),

('quarto','Organização','Tapete de Atividades',
 'Tapete com arco, brinquedos pendurados e espelho',
 1,1,'recomendado','IMPORTANTE','ATE_3_MESES',28,36,13,52,
 true,false,true,true,false,1,
 150,500,25,80,325,52,'usa','AGUARDAR_EUA',
 ARRAY['desenvolvimento','brinquedo'],true,1110),

('quarto','Iluminação','Luminária Infantil Dimmer',
 'Luminária com regulagem de brilho, ideal para amamentação noturna',
 1,1,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,34,0,208,
 false,false,false,true,false,1,
 80,300,20,60,190,40,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['quarto','iluminação'],true,1120),

('quarto','Organização','Cortina Blackout',
 'Cortina que bloqueia luz para melhorar o sono diurno',
 2,4,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,34,0,208,
 false,false,false,true,false,2,
 80,250,15,50,165,32,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['sono','quarto'],true,1130),

('quarto','Organização','Cesto de Roupas Sujas',
 'Cesto grande para roupinhas sujas do bebê',
 1,1,'conveniente','OPCIONAL','NO_NASCIMENTO',20,34,0,208,
 false,false,false,false,false,1,
 50,150,10,30,100,20,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['quarto','organização'],true,1140),

('quarto','Organização','Organizador de Gavetas Baby',
 'Divisórias e caixinhas organizadoras para roupinhas e fraldas',
 1,2,'conveniente','OPCIONAL','NO_NASCIMENTO',20,34,0,208,
 false,false,true,true,false,1,
 40,150,10,30,95,20,'qualquer','COMPRAR_AGORA_BRASIL',
 ARRAY['organização','quarto'],true,1150),

-- =============================================================
-- SONO (sort 2000+)
-- =============================================================
('sono','Cama','Saco de Dormir Bebê (verão)',
 'Saco de dormir leve para noites quentes, sem risco de sufocamento',
 2,4,'essencial','CRITICO','NO_NASCIMENTO',24,36,0,52,
 false,false,false,true,false,1,
 60,200,12,40,130,26,'qualquer','COMPRAR_AGORA_BRASIL',
 ARRAY['sono','segurança'],true,2010),

('sono','Cama','Saco de Dormir Bebê (inverno)',
 'Saco de dormir acolchoado para noites frias (TOG 2.5)',
 2,3,'recomendado','IMPORTANTE','NO_NASCIMENTO',24,36,0,52,
 false,false,false,true,false,1,
 80,250,20,50,165,35,'qualquer','COMPRAR_AGORA_BRASIL',
 ARRAY['sono','inverno'],true,2020),

('sono','Roupa de Cama','Lençol para Berço (kit 3)',
 'Lençóis 100% algodão com elástico, lavável na máquina',
 1,3,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,104,
 false,false,false,true,false,1,
 80,250,15,50,165,32,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['sono','quarto'],true,2030),

('sono','Roupa de Cama','Protetor Impermeável para Berço',
 'Protetor de colchão impermeável e macio',
 2,3,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,104,
 false,false,false,false,false,1,
 40,120,8,25,80,16,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['sono','higiene'],true,2040),

('sono','Roupa de Cama','Cobertor de Bebê',
 'Cobertor de malha ou fleece para uso no berço',
 2,4,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,36,0,52,
 false,false,false,true,false,1,
 40,150,8,30,95,19,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['sono','quarto'],true,2050),

('sono','Swaddle','Cueiro de Musselina (kit 4)',
 'Manta de musselina para enrolar, multifuncional',
 2,4,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,16,
 false,false,false,true,false,1,
 80,250,20,50,165,35,'qualquer','COMPRAR_AGORA_BRASIL',
 ARRAY['sono','enrolar'],true,2060),

('sono','Swaddle','Swaddle Zípado (Sleep Sack)',
 'Swaddle com zíper para facilitar trocas noturnas',
 2,4,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,36,0,16,
 false,false,false,true,false,1,
 80,250,15,40,165,27,'usa','AGUARDAR_EUA',
 ARRAY['sono','swaddle'],true,2070),

('sono','Eletrodoméstico','Máquina de Ruído Branco',
 'Som de ruído branco, batimentos cardíacos ou chuva para dormir',
 1,1,'recomendado','IMPORTANTE','NO_NASCIMENTO',24,36,0,52,
 false,false,true,true,false,1,
 80,300,15,50,190,32,'usa','AGUARDAR_EUA',
 ARRAY['sono','eletrônico'],true,2080),

('sono','Segurança','Redutor para Berço',
 'Almofada redutora para RN não escorregar no berço',
 1,1,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,34,0,13,
 false,false,false,true,false,1,
 80,250,15,50,165,32,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['sono','segurança','RN'],true,2090),

('sono','Segurança','Monitor de Respiração / Oxímetro',
 'Sensor que monitora respiração e saturação de O2 durante o sono',
 1,1,'conveniente','OPCIONAL','NO_NASCIMENTO',24,36,0,52,
 false,false,true,true,false,1,
 300,800,50,200,550,125,'usa','AGUARDAR_EUA',
 ARRAY['segurança','sono','monitoramento'],true,2100),

-- =============================================================
-- PASSEIO (sort 3000+)
-- =============================================================
('passeio','Carrinho','Carrinho Travel System',
 'Carrinho com bebe-conforto encaixável, reclinação total para RN',
 1,1,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,156,
 false,true,false,true,true,12,
 1000,4000,200,700,2500,450,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['passeio','RN'],true,3010),

('passeio','Carrinho','Carrinho Guarda-Chuva Leve',
 'Carrinho compacto e leve para partir de 6 meses',
 1,1,'recomendado','IMPORTANTE','ATE_6_MESES',32,36,26,208,
 true,true,true,true,false,5,
 400,1200,80,250,800,165,'usa','AGUARDAR_EUA',
 ARRAY['passeio','leve'],true,3020),

('passeio','Cadeirinha','Bebê Conforto (Grupo 0+)',
 'Cadeirinha para carro grupo 0+ (até 13kg), obrigatória por lei',
 1,1,'essencial','CRITICO','NO_NASCIMENTO',16,34,0,52,
 false,true,false,true,false,4,
 400,1600,80,350,1000,215,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['segurança','carro','obrigatório'],true,3030),

('passeio','Cadeirinha','Cadeirinha de Carro (Grupo 1)',
 'Cadeirinha 9-18kg, afrente e contra o sentido do veículo',
 1,1,'essencial','CRITICO','ATE_6_MESES',32,38,26,156,
 false,true,true,true,false,5,
 400,2000,80,400,1200,240,'usa','AGUARDAR_EUA',
 ARRAY['segurança','carro'],true,3040),

('passeio','Canguru','Canguru Ergonômico',
 'Portador ergonômico com suporte lombar, posição M do bebê',
 1,1,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,36,0,78,
 true,false,true,true,false,1,
 250,800,50,180,525,115,'usa','AGUARDAR_EUA',
 ARRAY['passeio','canguru','bonding'],true,3050),

('passeio','Canguru','Sling Elástico (Wrap)',
 'Pano longo para colo ergonômico de RN, favorece o bonding',
 1,1,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,36,0,26,
 true,false,true,true,false,1,
 150,400,30,80,275,55,'qualquer','COMPRAR_AGORA_BRASIL',
 ARRAY['canguru','RN','bonding'],true,3060),

('passeio','Bolsa','Bolsa Maternidade Funcional',
 'Bolsa grande com compartimentos organizados e trocador',
 1,1,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,156,
 false,false,false,true,false,1,
 100,400,25,80,250,52,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['passeio','organização'],true,3070),

('passeio','Acessórios','Capa de Chuva para Carrinho',
 'Capa impermeável universal para carrinho',
 1,1,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,36,0,208,
 false,false,true,false,false,1,
 40,120,8,25,80,16,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['passeio','chuva'],true,3080),

('passeio','Acessórios','Protetor Solar Bebê FPS 50+',
 'Protetor solar mineral para bebês com mais de 6 meses',
 1,3,'essencial','CRITICO','ATE_6_MESES',36,40,26,208,
 false,false,true,false,false,1,
 40,120,8,25,80,16,'qualquer','COMPRAR_AGORA_BRASIL',
 ARRAY['saúde','passeio'],true,3090),

('passeio','Acessórios','Mosquiteiro para Carrinho',
 'Rede fina para proteção contra insetos no carrinho',
 1,1,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,36,0,208,
 false,false,true,false,false,1,
 30,80,6,15,55,10,'qualquer','COMPRAR_AGORA_BRASIL',
 ARRAY['passeio','segurança'],true,3100),

('passeio','Acessórios','Organizador de Carrinho',
 'Bolsa que se prende ao cabo do carrinho com compartimentos',
 1,1,'conveniente','OPCIONAL','NO_NASCIMENTO',24,36,0,208,
 false,false,true,true,false,1,
 30,80,8,20,55,14,'usa','AGUARDAR_EUA',
 ARRAY['passeio','organização'],true,3110),

-- =============================================================
-- SEGURANÇA (sort 4000+)
-- =============================================================
('seguranca','Proteção','Grade para Escada',
 'Portão de segurança para escadas e portas, instalação permanente',
 1,2,'essencial','CRITICO','ATE_6_MESES',32,36,26,208,
 false,false,true,false,true,3,
 150,400,30,80,275,55,'usa','AGUARDAR_EUA',
 ARRAY['segurança','movimentação'],true,4010),

('seguranca','Proteção','Trava para Armário e Gaveta (kit 8)',
 'Travas de segurança para armários e gavetas ao alcance do bebê',
 1,2,'essencial','CRITICO','ATE_6_MESES',32,36,26,208,
 false,false,true,false,false,1,
 30,80,8,20,55,14,'usa','AGUARDAR_EUA',
 ARRAY['segurança','proteção'],true,4020),

('seguranca','Proteção','Protetor de Tomada (kit 12)',
 'Tampinhas de segurança para tomadas elétricas',
 2,3,'essencial','CRITICO','NO_NASCIMENTO',20,36,0,208,
 false,false,true,false,false,1,
 15,40,3,10,27,6,'qualquer','COMPRAR_AGORA_BRASIL',
 ARRAY['segurança','elétrico'],true,4030),

('seguranca','Proteção','Protetor de Canto de Mesa (kit)',
 'Espumas ou silicone para proteger cantos pontiagudos',
 1,2,'recomendado','IMPORTANTE','ATE_6_MESES',32,36,26,208,
 false,false,true,false,false,1,
 20,60,5,15,40,10,'qualquer','COMPRAR_AGORA_BRASIL',
 ARRAY['segurança','proteção'],true,4040),

('seguranca','Proteção','Cerca de Segurança (Cercadinho)',
 'Cercadinho modular para delimitar área segura de brincadeiras',
 1,1,'recomendado','IMPORTANTE','ATE_6_MESES',32,36,26,156,
 true,true,true,false,true,8,
 200,600,50,150,400,100,'usa','AGUARDAR_EUA',
 ARRAY['segurança','brincadeiras'],true,4050),

('seguranca','Proteção','Tapete Antiderrapante para Banheiro',
 'Tapete com ventosas para banheiro e área do banho',
 1,2,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,36,0,208,
 false,false,true,false,false,1,
 20,60,5,15,40,10,'qualquer','COMPRAR_AGORA_BRASIL',
 ARRAY['segurança','banho'],true,4060),

('seguranca','Monitoramento','Câmera Wi-Fi para Quarto',
 'Câmera HD com visão noturna e app no celular',
 1,1,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,36,0,208,
 false,false,true,true,false,1,
 150,500,30,100,325,65,'usa','AGUARDAR_EUA',
 ARRAY['segurança','monitoramento'],true,4070),

('seguranca','Proteção','Protetor de Cabeceira de Cama',
 'Almofada para lateral da cama dos pais (co-sleeping)',
 1,1,'conveniente','OPCIONAL','NO_NASCIMENTO',20,34,0,26,
 false,false,true,true,false,1,
 80,200,15,40,140,27,'qualquer','COMPRAR_AGORA_BRASIL',
 ARRAY['segurança','sono','co-sleeping'],true,4080),

-- =============================================================
-- ALIMENTAÇÃO (sort 5000+)
-- =============================================================
('alimentacao','Amamentação','Bomba de Leite Elétrica Dupla',
 'Bomba elétrica de extração dupla, silenciosa e portátil',
 1,1,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,52,
 false,false,false,true,false,1,
 400,1800,80,300,1100,190,'usa','AGUARDAR_EUA',
 ARRAY['amamentação','alimentação'],true,5010),

('alimentacao','Amamentação','Bomba de Leite Manual',
 'Bomba manual para uso ocasional ou quando sem energia',
 1,1,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,34,0,52,
 false,false,false,true,false,1,
 80,250,15,50,165,32,'usa','AGUARDAR_EUA',
 ARRAY['amamentação','alimentação'],true,5020),

('alimentacao','Mamadeiras','Mamadeiras Anticolíca (kit 3)',
 'Mamadeiras com sistema anticolíca e bico ortodôntico',
 1,2,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,36,0,52,
 false,false,true,true,false,1,
 80,300,15,60,190,37,'usa','AGUARDAR_EUA',
 ARRAY['alimentação','mamadeira'],true,5030),

('alimentacao','Esterilização','Esterilizador Elétrico a Vapor',
 'Esterilizador para mamadeiras, bicos e chupetas',
 1,1,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,34,0,104,
 false,false,true,true,false,3,
 150,500,30,100,325,65,'usa','AGUARDAR_EUA',
 ARRAY['higiene','alimentação'],true,5040),

('alimentacao','Esterilização','Sacos para Esterilizar no Micro-ondas (kit 5)',
 'Sacos reutilizáveis para esterilização rápida no micro-ondas',
 1,3,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,36,0,104,
 false,false,true,true,false,1,
 20,60,5,12,40,8,'qualquer','COMPRAR_AGORA_BRASIL',
 ARRAY['higiene','alimentação','prático'],true,5050),

('alimentacao','Armazenamento','Sacos para Congelar Leite Materno (50 unid)',
 'Sacos esterilizados para armazenar e congelar leite materno',
 2,5,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,34,0,52,
 false,false,true,true,false,1,
 30,80,8,20,55,14,'usa','AGUARDAR_EUA',
 ARRAY['amamentação','armazenamento'],true,5060),

('alimentacao','Cadeirão','Cadeirão de Alimentação',
 'Cadeira de refeição com bandeja, regulável e reclinável',
 1,1,'essencial','CRITICO','ATE_6_MESES',28,36,26,208,
 false,true,true,true,true,6,
 250,800,50,200,525,125,'usa','AGUARDAR_EUA',
 ARRAY['alimentação','mobília'],true,5070),

('alimentacao','Utensílios','Babadores de Silicone com Bolso (kit 3)',
 'Babadores impermeáveis com bolso coletor',
 1,3,'essencial','CRITICO','NO_NASCIMENTO',20,36,0,104,
 false,false,false,true,false,1,
 40,120,8,25,80,16,'usa','AGUARDAR_EUA',
 ARRAY['alimentação','higiene'],true,5080),

('alimentacao','Utensílios','Babadores de Pano (kit 5)',
 'Babadores de tecido absorvente para cuspinhos e salivação',
 2,4,'essencial','CRITICO','NO_NASCIMENTO',20,36,0,52,
 false,false,false,true,false,1,
 30,100,8,20,65,14,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['alimentação','higiene'],true,5090),

('alimentacao','Utensílios','Babador de Manga Comprida (2 unid)',
 'Cobre os braços durante as refeições, ideal para inicio alimentação',
 1,2,'recomendado','IMPORTANTE','ATE_6_MESES',28,36,26,104,
 false,false,true,true,false,1,
 30,80,8,20,55,14,'usa','AGUARDAR_EUA',
 ARRAY['alimentação'],true,5100),

('alimentacao','Utensílios','Escovas para Lavar Mamadeiras (kit)',
 'Escovas macias para limpar mamadeiras, bicos e canudos',
 1,1,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,36,0,104,
 false,false,false,false,false,1,
 20,60,5,12,40,8,'qualquer','COMPRAR_AGORA_BRASIL',
 ARRAY['higiene','alimentação'],true,5110),

('alimentacao','Transição','Copo de Transição com Bico',
 'Copo com bico mole para fase de transição do peito/mamadeira',
 2,3,'recomendado','IMPORTANTE','ATE_6_MESES',28,38,26,52,
 false,false,true,true,false,1,
 25,80,5,15,52,10,'usa','AGUARDAR_EUA',
 ARRAY['alimentação','transição'],true,5120),

('alimentacao','Papinha','Processador de Alimentos Baby',
 'Mini processador ou mixer para papinhas e purês',
 1,1,'recomendado','IMPORTANTE','ATE_6_MESES',28,36,26,104,
 false,false,true,true,false,1,
 150,500,30,80,325,55,'usa','AGUARDAR_EUA',
 ARRAY['alimentação','papinha'],true,5130),

('alimentacao','Papinha','Potes para Papinha (kit 10)',
 'Potes de vidro ou plástico BPA-free para papinhas',
 1,2,'recomendado','IMPORTANTE','ATE_6_MESES',28,36,26,104,
 false,false,true,true,false,1,
 30,80,8,20,55,14,'qualquer','COMPRAR_AGORA_BRASIL',
 ARRAY['alimentação','papinha'],true,5140),

('alimentacao','Papinha','Colheres de Silicone Baby (kit 4)',
 'Colheres macias de silicone para os primeiros alimentos',
 1,2,'recomendado','IMPORTANTE','ATE_6_MESES',28,36,26,104,
 false,false,true,true,false,1,
 20,60,5,12,40,8,'usa','AGUARDAR_EUA',
 ARRAY['alimentação','papinha'],true,5150),

('alimentacao','Papinha','Tigela com Ventosa de Silicone (kit 2)',
 'Tigelas que grudam na mesa e não tombam',
 1,2,'recomendado','IMPORTANTE','ATE_6_MESES',28,36,26,104,
 false,false,true,true,false,1,
 30,80,8,20,55,14,'usa','AGUARDAR_EUA',
 ARRAY['alimentação','papinha'],true,5160),

('alimentacao','Aquecimento','Aquecedor de Mamadeiras',
 'Aquecedor elétrico ou portátil para manter temperatura ideal',
 1,1,'conveniente','OPCIONAL','NO_NASCIMENTO',20,36,0,52,
 false,false,true,true,false,1,
 60,200,12,40,130,26,'usa','AGUARDAR_EUA',
 ARRAY['alimentação','prático'],true,5170),

-- =============================================================
-- AMAMENTAÇÃO (sort 6000+)
-- =============================================================
('amamentacao','Conforto','Travesseiro de Amamentação',
 'Travesseiro em forma de C para apoio durante a amamentação',
 1,1,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,26,
 true,false,false,true,false,1,
 80,300,20,60,190,40,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['amamentação','conforto'],true,6010),

('amamentacao','Proteção','Conchas Protetoras para Seios',
 'Conchas de silicone para coletar leite que vaza e proteger mamilos',
 1,1,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,34,0,26,
 false,false,false,true,false,1,
 40,120,10,25,80,17,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['amamentação'],true,6020),

('amamentacao','Absorção','Absorventes para Seio Descartáveis (60 unid)',
 'Absorventes descartáveis para prevenir vazamentos',
 3,6,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,26,
 false,false,false,false,false,1,
 20,60,5,15,40,10,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['amamentação'],true,6030),

('amamentacao','Absorção','Absorventes para Seio Laváveis (kit 8)',
 'Absorventes de tecido reutilizáveis, ecológicos',
 1,2,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,34,0,26,
 false,false,false,true,false,1,
 40,120,10,25,80,17,'qualquer','COMPRAR_AGORA_BRASIL',
 ARRAY['amamentação','sustentável'],true,6040),

('amamentacao','Proteção','Protetor de Mamilo de Silicone',
 'Protetor fino que alivia dores e fissuras no mamilo',
 1,1,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,34,0,26,
 false,false,false,false,false,1,
 30,80,8,15,55,11,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['amamentação','saúde'],true,6050),

('amamentacao','Proteção','Lanolina para Mamilos',
 'Creme de lanolina 100% puro para cuidar das fissuras',
 2,4,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,26,
 false,false,false,false,false,1,
 30,80,8,20,55,14,'qualquer','COMPRAR_AGORA_BRASIL',
 ARRAY['amamentação','saúde'],true,6060),

('amamentacao','Vestuário','Sutiã para Amamentação (3 unid)',
 'Sutiã com abertura frontal, confortável e de suporte',
 1,2,'essencial','CRITICO','NO_NASCIMENTO',24,36,0,52,
 false,false,false,true,false,1,
 80,250,20,50,165,35,'qualquer','COMPRAR_AGORA_BRASIL',
 ARRAY['amamentação','roupa mamãe'],true,6070),

('amamentacao','Vestuário','Blusas para Amamentação (kit 3)',
 'Blusas com acesso frontal discreto para amamentar em público',
 1,2,'recomendado','IMPORTANTE','NO_NASCIMENTO',24,36,0,52,
 false,false,true,true,false,1,
 80,250,20,50,165,35,'qualquer','COMPRAR_AGORA_BRASIL',
 ARRAY['amamentação','roupa mamãe'],true,6080),

('amamentacao','Conforto','Compressas Térmicas para Seios',
 'Compressas quente/frio para ingurgitamento e mastite',
 1,2,'recomendado','IMPORTANTE','NO_NASCIMENTO',24,36,0,26,
 false,false,false,true,false,1,
 30,80,8,20,55,14,'qualquer','COMPRAR_AGORA_BRASIL',
 ARRAY['amamentação','saúde'],true,6090),

('amamentacao','Retirada','Bomba Manual de Emergência',
 'Bomba manual extra para situações sem energia elétrica',
 1,1,'conveniente','OPCIONAL','NO_NASCIMENTO',20,34,0,26,
 false,false,true,false,false,1,
 60,200,12,40,130,26,'qualquer','COMPRAR_AGORA_BRASIL',
 ARRAY['amamentação'],true,6100),

-- =============================================================
-- HIGIENE (sort 7000+)
-- =============================================================
('higiene','Essenciais','Kit Higiene Completo',
 'Escovinha de cabelo, pente, cortador de unhas, tesoura curva',
 1,1,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,208,
 false,false,false,true,false,1,
 40,150,10,30,95,20,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['higiene','essencial'],true,7010),

('higiene','Termômetros','Termômetro Digital Axilar',
 'Termômetro de leitura rápida para medição axilar',
 2,2,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,208,
 false,false,false,true,false,1,
 30,80,8,20,55,14,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['saúde','higiene'],true,7020),

('higiene','Termômetros','Termômetro de Testa Infravermelho',
 'Termômetro sem contato, leitura instantânea na testa',
 1,1,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,34,0,208,
 false,false,true,true,false,1,
 80,300,20,60,190,40,'usa','AGUARDAR_EUA',
 ARRAY['saúde','higiene'],true,7030),

('higiene','Nariz','Aspirador Nasal Manual',
 'Aspirador tipo bulbo ou com boquilha para desobstruir nariz',
 2,2,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,208,
 false,false,false,false,false,1,
 20,60,5,15,40,10,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['saúde','higiene'],true,7040),

('higiene','Nariz','Aspirador Nasal Elétrico',
 'Aspirador elétrico recarregável, mais eficiente para gripes',
 1,1,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,36,0,104,
 false,false,true,true,false,1,
 80,250,20,50,165,35,'usa','AGUARDAR_EUA',
 ARRAY['saúde','higiene'],true,7050),

('higiene','Fralda','Fraldas Descartáveis RN 0-4kg (2 pacotes)',
 'Fraldas para recém-nascido com cordão umbilical recortado',
 2,4,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,4,
 false,false,false,false,false,4,
 25,70,8,20,47,14,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['higiene','fralda','RN'],true,7060),

('higiene','Fralda','Fraldas Descartáveis Tamanho P (4 pacotes)',
 'Fraldas tamanho P para bebês de 4-8kg',
 4,8,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,13,
 false,false,false,false,false,5,
 30,80,10,25,55,17,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['higiene','fralda'],true,7070),

('higiene','Fralda','Fraldas Descartáveis Tamanho M (4 pacotes)',
 'Fraldas tamanho M para bebês de 7-10kg — comprar com antecedência',
 4,8,'essencial','CRITICO','ATE_3_MESES',28,36,13,26,
 false,false,true,false,false,6,
 35,90,12,30,62,21,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['higiene','fralda'],true,7080),

('higiene','Fralda','Lenços Umedecidos sem Perfume (10 pacotes)',
 'Lenços umedecidos hipoalergênicos e sem fragrância',
 10,20,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,208,
 false,false,false,false,false,3,
 8,20,2,5,14,3,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['higiene','fralda'],true,7090),

('higiene','Fralda','Pomada para Assaduras (3 tubos)',
 'Pomada à base de óxido de zinco para prevenir assaduras',
 3,6,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,208,
 false,false,false,false,false,1,
 15,40,4,10,27,7,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['higiene','saúde'],true,7100),

('higiene','Fralda','Lixeira para Fraldas (Diaper Pail)',
 'Lixeira com vedação antiodor para fraldas sujas',
 1,1,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,34,0,208,
 false,false,true,true,false,3,
 80,300,20,60,190,40,'usa','AGUARDAR_EUA',
 ARRAY['higiene','fralda','quarto'],true,7110),

('higiene','Fralda','Refil para Lixeira de Fraldas',
 'Refis de substituição para lixeira de fraldas',
 2,6,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,36,0,208,
 false,false,true,false,false,1,
 30,80,8,20,55,14,'usa','AGUARDAR_EUA',
 ARRAY['higiene','fralda'],true,7120),

('higiene','Fralda','Trocador de Chão Impermeável',
 'Trocador portátil impermeável e lavável, sem produto químico',
 2,3,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,36,0,208,
 false,false,false,true,false,1,
 30,80,8,20,55,14,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['higiene','fralda','portátil'],true,7130),

('higiene','Pele','Shampoo Infantil sem Parabenos',
 'Shampoo suave sem lágrimas e sem parabenos',
 2,4,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,208,
 false,false,false,false,false,1,
 15,40,5,12,27,8,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['higiene','banho'],true,7140),

('higiene','Pele','Sabonete Líquido Infantil pH Neutro',
 'Sabonete pH neutro específico para pele do bebê',
 2,4,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,208,
 false,false,false,false,false,1,
 12,35,4,10,23,7,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['higiene','banho'],true,7150),

('higiene','Pele','Hidratante Corporal Infantil',
 'Loção ou óleo hidratante para pele delicada do bebê',
 2,4,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,208,
 false,false,false,false,false,1,
 15,40,5,12,27,8,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['higiene','pele'],true,7160),

('higiene','Essenciais','Algodão Hidrófilo (2 pacotes)',
 'Algodão para limpeza de olhos, umbigo e dobrinhas',
 2,4,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,208,
 false,false,false,false,false,1,
 5,15,2,5,10,3,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['higiene'],true,7170),

('higiene','Umbigo','Kit Cuidados com Coto Umbilical',
 'Álcool 70%, gaze e curativo para cuidar do coto',
 1,2,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,4,
 false,false,false,false,false,1,
 15,40,4,10,27,7,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['higiene','saúde','RN'],true,7180),

('higiene','Portátil','Bolsa Trocador Portátil',
 'Trocador dobrável com compartimentos para passeios',
 1,1,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,34,0,208,
 false,false,false,true,false,1,
 60,200,15,40,130,27,'usa','AGUARDAR_EUA',
 ARRAY['higiene','passeio','portátil'],true,7190),

-- =============================================================
-- BANHO (sort 8000+)
-- =============================================================
('banho','Banheira','Banheira com Suporte Antiderrapante',
 'Banheira ergonômica com suporte que firma na banheira adulto',
 1,1,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,52,
 true,false,false,true,false,2,
 80,250,15,50,165,32,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['banho','essencial'],true,8010),

('banho','Banheira','Banheira Portátil Dobrável',
 'Banheira dobrável para viagens e espaços pequenos',
 1,1,'conveniente','OPCIONAL','NO_NASCIMENTO',20,36,0,52,
 true,false,true,true,false,1,
 80,250,15,50,165,32,'usa','AGUARDAR_EUA',
 ARRAY['banho','viagem','portátil'],true,8020),

('banho','Temperatura','Termômetro de Água para Banho',
 'Termômetro que indica a temperatura ideal da água (37°C)',
 1,1,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,208,
 false,false,false,true,false,1,
 20,60,5,15,40,10,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['banho','segurança'],true,8030),

('banho','Toalhas','Toalha com Capuz de Algodão (kit 3)',
 'Toalhas com capuz para envolver o bebê após o banho',
 3,5,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,104,
 false,false,false,true,false,1,
 40,150,10,30,95,20,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['banho','essencial'],true,8040),

('banho','Esponja','Esponja de Banho Infantil (2)',
 'Esponja macia hipoalergênica para banho do bebê',
 2,2,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,34,0,52,
 false,false,false,false,false,1,
 10,30,3,8,20,5,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['banho'],true,8050),

('banho','Assento','Assento de Banho com Ventosas',
 'Cadeira de suporte para bebê sentar na banheira por volta dos 6m',
 1,1,'recomendado','IMPORTANTE','ATE_6_MESES',32,36,26,52,
 false,false,true,true,false,1,
 40,120,8,25,80,16,'usa','AGUARDAR_EUA',
 ARRAY['banho','segurança'],true,8060),

('banho','Acessórios','Luva de Banho',
 'Luva de borracha ou esponja para ensaboar o bebê',
 1,2,'conveniente','OPCIONAL','NO_NASCIMENTO',20,36,0,52,
 false,false,false,false,false,1,
 10,30,3,8,20,5,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['banho'],true,8070),

('banho','Acessórios','Duchinhas Portáteis (kit 20)',
 'Panos ou fraldas umedecidas para higiene rápida em viagens',
 1,3,'conveniente','OPCIONAL','NO_NASCIMENTO',20,36,0,104,
 false,false,true,false,false,1,
 20,60,5,15,40,10,'qualquer','COMPRAR_AGORA_BRASIL',
 ARRAY['banho','viagem','portátil'],true,8080),

-- =============================================================
-- SAÚDE (sort 9000+)
-- =============================================================
('saude','Primeiros Socorros','Kit Primeiros Socorros Baby',
 'Termômetro, esparadrapo, gaze, micropore, luvas descartáveis',
 1,1,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,208,
 false,false,false,true,false,1,
 50,150,12,30,100,21,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['saúde','emergência'],true,9010),

('saude','Medicamentos','Vitamina D em Gotas',
 'Suplementação de vitamina D conforme orientação pediátrica',
 1,3,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,26,
 false,false,false,false,false,1,
 20,60,5,15,40,10,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['saúde','nutrição'],true,9020),

('saude','Medicamentos','Analgésico Infantil (prescrição)',
 'Paracetamol infantil — com orientação do pediatra',
 1,2,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,208,
 false,false,false,false,false,1,
 10,30,3,8,20,5,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['saúde','medicamento'],true,9030),

('saude','Medicamentos','Soro Fisiológico 0,9% (kit 20 ampolas)',
 'Para higiene nasal e limpeza dos olhos',
 2,4,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,208,
 false,false,false,false,false,1,
 15,40,4,10,27,7,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['saúde','higiene'],true,9040),

('saude','Aparelhos','Nebulizador / Inalador Infantil',
 'Inalador compressor para nebulização com máscara infantil',
 1,1,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,36,0,208,
 true,false,true,true,false,2,
 150,500,30,100,325,65,'usa','AGUARDAR_EUA',
 ARRAY['saúde','respiratório'],true,9050),

('saude','Aparelhos','Oxímetro de Pulso Pediátrico',
 'Oxímetro com sensor para dedo de bebê',
 1,1,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,36,0,208,
 false,false,true,true,false,1,
 80,250,15,50,165,32,'usa','AGUARDAR_EUA',
 ARRAY['saúde','monitoramento'],true,9060),

('saude','Aparelhos','Otoscópio Infantil',
 'Otoscópio para verificar ouvidos em casa antes de ir ao médico',
 1,1,'conveniente','OPCIONAL','NO_NASCIMENTO',20,36,0,208,
 false,false,true,true,false,1,
 80,300,15,60,190,37,'usa','AGUARDAR_EUA',
 ARRAY['saúde'],true,9070),

('saude','Conforto','Chupeta Ortodôntica (kit 3)',
 'Chupeta com formato anatômico e bico ortodôntico',
 3,6,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,36,0,52,
 false,false,false,true,false,1,
 15,40,4,10,27,7,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['conforto','sono'],true,9080),

('saude','Conforto','Porta-Chupeta com Prendedor (kit 3)',
 'Cordão prendedor de chupeta com clipe de segurança',
 3,6,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,36,0,52,
 false,false,false,true,false,1,
 15,40,4,10,27,7,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['conforto'],true,9090),

('saude','Conforto','Mordedor Resfriável (kit 3)',
 'Mordedor para alívio da dentição, pode ser resfriado na geladeira',
 3,6,'recomendado','IMPORTANTE','ATE_3_MESES',28,36,13,52,
 false,false,true,true,false,1,
 15,40,4,10,27,7,'usa','AGUARDAR_EUA',
 ARRAY['conforto','dentição'],true,9100),

-- =============================================================
-- ROUPAS (sort 10000+)
-- =============================================================
-- Recém-Nascido (RN - 0 a 3 kg)
('roupas','RN (até 3kg)','Body Manga Curta RN (kit 5)',
 'Bodies de algodão manga curta para RN, fechamento com botões',
 1,2,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,13,
 false,false,false,true,false,1,
 40,120,10,30,80,20,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['roupas','RN','body'],true,10010),

('roupas','RN (até 3kg)','Body Manga Longa RN (kit 3)',
 'Bodies de algodão manga longa para RN',
 1,2,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,13,
 false,false,false,true,false,1,
 40,120,10,30,80,20,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['roupas','RN','body'],true,10020),

('roupas','RN (até 3kg)','Macacão Inteiro RN (kit 3)',
 'Macacão com zíper ou botões, prático para trocas noturnas',
 1,2,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,13,
 false,false,false,true,false,1,
 50,150,12,35,100,23,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['roupas','RN'],true,10030),

('roupas','RN (até 3kg)','Calças Moles RN (kit 3)',
 'Calças de malha com elástico macio para RN',
 1,2,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,13,
 false,false,false,true,false,1,
 30,90,8,20,60,14,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['roupas','RN'],true,10040),

('roupas','RN (até 3kg)','Meias Antiderrapante RN (kit 6 pares)',
 'Meias de algodão com sola antiderrapante',
 2,3,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,13,
 false,false,false,true,false,1,
 20,60,5,15,40,10,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['roupas','RN'],true,10050),

('roupas','RN (até 3kg)','Luvinhas de Algodão RN (3 pares)',
 'Luvinhas para evitar que o bebê se arranhe',
 1,2,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,34,0,8,
 false,false,false,true,false,1,
 10,30,3,8,20,5,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['roupas','RN','segurança'],true,10060),

('roupas','RN (até 3kg)','Touquinha de Algodão RN (3 unid)',
 'Touca macia para manter a temperatura do RN',
 1,2,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,34,0,8,
 false,false,false,true,false,1,
 10,30,3,8,20,5,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['roupas','RN'],true,10070),

('roupas','RN (até 3kg)','Sapatinhos Macios RN (2 pares)',
 'Sapatinhos sem sola rígida para bebê que não anda',
 2,3,'conveniente','OPCIONAL','NO_NASCIMENTO',20,34,0,13,
 false,false,false,true,false,1,
 20,60,5,15,40,10,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['roupas','RN'],true,10080),

('roupas','RN (até 3kg)','Manta de Algodão (kit 3)',
 'Mantas multiuso para enrolar, cobrir no carrinho ou amamentar',
 3,4,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,26,
 false,false,false,true,false,1,
 40,150,10,30,95,20,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['roupas','sono','multiuso'],true,10090),

-- 0-3 meses
('roupas','0-3 meses','Body Manga Curta 0-3m (kit 5)',
 'Bodies de algodão para fase 0-3 meses',
 1,2,'essencial','CRITICO','NO_NASCIMENTO',20,36,0,13,
 false,false,true,true,false,1,
 40,120,10,30,80,20,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['roupas','0-3m'],true,10100),

('roupas','0-3 meses','Body Manga Longa 0-3m (kit 3)',
 'Bodies manga longa para fase 0-3 meses',
 1,2,'essencial','CRITICO','NO_NASCIMENTO',20,36,0,13,
 false,false,true,true,false,1,
 40,120,10,30,80,20,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['roupas','0-3m'],true,10110),

('roupas','0-3 meses','Macacão 0-3m (kit 3)',
 'Macacões confortáveis para fase 0-3 meses',
 1,2,'essencial','CRITICO','NO_NASCIMENTO',20,36,0,13,
 false,false,true,true,false,1,
 50,150,12,35,100,23,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['roupas','0-3m'],true,10120),

('roupas','0-3 meses','Meias 0-3m (kit 6 pares)',
 'Meias de algodão para fase 0-3 meses',
 2,3,'essencial','CRITICO','NO_NASCIMENTO',20,36,0,13,
 false,false,true,true,false,1,
 20,60,5,15,40,10,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['roupas','0-3m'],true,10130),

-- 3-6 meses
('roupas','3-6 meses','Body Manga Curta 3-6m (kit 5)',
 'Bodies de algodão para fase 3-6 meses',
 1,2,'essencial','CRITICO','ATE_3_MESES',20,36,13,26,
 false,false,true,true,false,1,
 40,120,10,30,80,20,'usa','AGUARDAR_EUA',
 ARRAY['roupas','3-6m'],true,10140),

('roupas','3-6 meses','Macacão 3-6m (kit 3)',
 'Macacões e roupinhas para fase 3-6 meses',
 1,2,'essencial','CRITICO','ATE_3_MESES',20,36,13,26,
 false,false,true,true,false,1,
 50,150,12,35,100,23,'usa','AGUARDAR_EUA',
 ARRAY['roupas','3-6m'],true,10150),

-- 6-9 meses
('roupas','6-9 meses','Body e Roupas 6-9m (kit)',
 'Kit de roupinhas para fase 6-9 meses',
 1,2,'recomendado','IMPORTANTE','ATE_6_MESES',28,38,26,39,
 false,false,true,true,false,1,
 50,150,12,35,100,23,'usa','AGUARDAR_EUA',
 ARRAY['roupas','6-9m'],true,10160),

-- Especiais
('roupas','Especiais','Macacão de Inverno / Snowsuit',
 'Macacão acolchoado para frio intenso',
 2,2,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,36,0,26,
 false,false,true,true,false,2,
 60,200,15,50,130,32,'usa','AGUARDAR_EUA',
 ARRAY['roupas','inverno'],true,10170),

('roupas','Especiais','Casaco Leve (kit 2)',
 'Casacos de frio moderado para diversas estações',
 2,3,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,36,0,52,
 false,false,true,true,false,1,
 40,150,10,30,95,20,'usa','AGUARDAR_EUA',
 ARRAY['roupas','casaco'],true,10180),

('roupas','Especiais','Collant / Meia-Calça (kit 3)',
 'Collants de malha para frio e conforto abdominal',
 3,4,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,36,0,26,
 false,false,true,true,false,1,
 15,40,4,10,27,7,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['roupas','inverno'],true,10190),

('roupas','Especiais','Pijama 2 Peças (kit 3)',
 'Pijamas confortáveis para uso diário',
 3,4,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,36,0,26,
 false,false,false,true,false,1,
 30,80,8,20,55,14,'qualquer','COMPRAR_AGORA_BRASIL',
 ARRAY['roupas','sono'],true,10200),

-- =============================================================
-- BRINQUEDOS & DESENVOLVIMENTO (sort 11000+)
-- =============================================================
('brinquedos','0-3 meses','Chocalho de Alta Contraste',
 'Chocalho com estampas preto e branco para estimulação visual',
 2,4,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,36,0,13,
 false,false,true,true,false,1,
 20,60,5,15,40,10,'qualquer','COMPRAR_AGORA_BRASIL',
 ARRAY['desenvolvimento','visual','0-3m'],true,11010),

('brinquedos','0-3 meses','Mordedor de Silicone (kit 3)',
 'Mordedor macio de silicone sem BPA para estimulação oral',
 3,6,'recomendado','IMPORTANTE','ATE_3_MESES',20,36,13,26,
 false,false,true,true,false,1,
 15,40,4,10,27,7,'usa','AGUARDAR_EUA',
 ARRAY['desenvolvimento','dentição'],true,11020),

('brinquedos','0-3 meses','Brinquedo de Estimulação Tátil (kit)',
 'Cubinhos, aros e bolas com diferentes texturas',
 1,2,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,36,0,26,
 false,false,true,true,false,1,
 30,80,8,20,55,14,'usa','AGUARDAR_EUA',
 ARRAY['desenvolvimento','tátil'],true,11030),

('brinquedos','0-6 meses','Livros de Tecido / Pano (kit 5)',
 'Livros macios com cores vivas, texturas e espelho',
 1,3,'recomendado','IMPORTANTE','NO_NASCIMENTO',24,36,0,52,
 false,false,true,true,false,1,
 20,60,5,15,40,10,'usa','AGUARDAR_EUA',
 ARRAY['desenvolvimento','leitura'],true,11040),

('brinquedos','0-6 meses','Espelho de Estimulação para Carrinho',
 'Espelho inquebrável para bebê se ver, estimula autoconsciência',
 1,1,'recomendado','IMPORTANTE','NO_NASCIMENTO',24,36,0,26,
 false,false,true,true,false,1,
 15,40,4,10,27,7,'usa','AGUARDAR_EUA',
 ARRAY['desenvolvimento','visual'],true,11050),

('brinquedos','3-6 meses','Brinquedos de Banho (kit)',
 'Brinquedos de borracha e plástico para a hora do banho',
 1,2,'recomendado','IMPORTANTE','ATE_3_MESES',24,36,13,52,
 false,false,true,true,false,1,
 20,60,5,15,40,10,'usa','AGUARDAR_EUA',
 ARRAY['desenvolvimento','banho'],true,11060),

('brinquedos','3-6 meses','Play Gym com Arco de Atividades',
 'Tapete com arco, 5 brinquedos pendurados e espelho',
 1,1,'essencial','CRITICO','ATE_3_MESES',24,36,13,26,
 true,false,true,true,false,2,
 150,500,25,80,325,52,'usa','AGUARDAR_EUA',
 ARRAY['desenvolvimento','motor','visual'],true,11070),

('brinquedos','6+ meses','Blocos de Montar Soft (kit 20)',
 'Blocos macios de espuma, seguros para bebês',
 1,1,'recomendado','IMPORTANTE','ATE_6_MESES',32,38,26,52,
 false,false,true,true,false,1,
 50,150,12,30,100,21,'usa','AGUARDAR_EUA',
 ARRAY['desenvolvimento','motor'],true,11080),

('brinquedos','6+ meses','Bola de Estimulação (3 tamanhos)',
 'Bolas de texturas variadas para estimulação motora',
 1,1,'recomendado','IMPORTANTE','ATE_3_MESES',28,38,13,52,
 false,false,true,true,false,1,
 20,60,5,15,40,10,'qualquer','COMPRAR_AGORA_BRASIL',
 ARRAY['desenvolvimento','motor'],true,11090),

('brinquedos','6+ meses','Brinquedo de Empurrar / Andador',
 'Andador de madeira ou plástico para estimular os primeiros passos',
 1,1,'recomendado','IMPORTANTE','ATE_6_MESES',32,36,26,78,
 true,false,true,true,true,4,
 100,300,25,60,200,42,'usa','AGUARDAR_EUA',
 ARRAY['desenvolvimento','motor'],true,11100),

('brinquedos','Sonoros','Piano de Chão',
 'Piano infantil que toca notas e músicas ao toque dos pés',
 1,1,'conveniente','OPCIONAL','ATE_3_MESES',28,38,13,52,
 true,false,true,true,false,1,
 80,250,15,50,165,32,'usa','AGUARDAR_EUA',
 ARRAY['desenvolvimento','musical'],true,11110),

-- =============================================================
-- MATERNIDADE (sort 12000+)
-- =============================================================
('maternidade','Roupa','Camisola para o Parto',
 'Camisola que abre na frente, para facilitar amamentação e parto',
 1,2,'essencial','CRITICO','NO_NASCIMENTO',32,36,0,26,
 false,false,false,true,false,1,
 60,200,12,40,130,26,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['maternidade','parto'],true,12010),

('maternidade','Roupa','Pijama de Maternidade (2 unid)',
 'Pijama confortável com manga longa, para pós-parto na maternidade',
 2,3,'essencial','CRITICO','NO_NASCIMENTO',32,36,0,26,
 false,false,false,true,false,1,
 80,250,15,50,165,32,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['maternidade','pós-parto'],true,12020),

('maternidade','Higiene','Absorvente Pós-Parto (2 pacotes)',
 'Absorventes extra-noturnos para lóquio pós-parto',
 2,4,'essencial','CRITICO','NO_NASCIMENTO',32,36,0,8,
 false,false,false,false,false,1,
 20,60,5,15,40,10,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['maternidade','saúde','pós-parto'],true,12030),

('maternidade','Higiene','Calcinha Descartável (kit 5)',
 'Calcinhas descartáveis para uso na maternidade',
 5,10,'essencial','CRITICO','NO_NASCIMENTO',32,36,0,4,
 false,false,false,false,false,1,
 20,60,5,15,40,10,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['maternidade'],true,12040),

('maternidade','Documentos','Documentos para Maternidade (kit)',
 'Carteira de identidade, plano de saúde, cartão pré-natal, plano de parto',
 1,1,'essencial','CRITICO','NO_NASCIMENTO',32,36,0,4,
 false,false,false,false,false,1,
 0,0,0,0,0,0,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['maternidade','documentos','essencial'],true,12050),

('maternidade','Conforto','Meias de Compressão',
 'Meias de compressão para prevenir trombose no pós-parto',
 2,2,'recomendado','IMPORTANTE','NO_NASCIMENTO',32,36,0,8,
 false,false,false,false,false,1,
 30,80,8,20,55,14,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['maternidade','saúde'],true,12060),

('maternidade','Conforto','Travesseiro para Apoio na Cama',
 'Travesseiro extra para conforto no hospital',
 1,1,'conveniente','OPCIONAL','NO_NASCIMENTO',32,36,0,4,
 true,false,false,false,false,1,
 40,120,8,25,80,16,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['maternidade','conforto'],true,12070),

('maternidade','Beleza','Necessaire de Higiene Pessoal',
 'Shampoo, condicionador, escova de dentes, cremes para o hospital',
 1,1,'recomendado','IMPORTANTE','NO_NASCIMENTO',32,36,0,4,
 false,false,false,false,false,1,
 30,80,8,20,55,14,'qualquer','COMPRAR_AGORA_BRASIL',
 ARRAY['maternidade','higiene'],true,12080),

('maternidade','Bebê na Mala','Roupa para Saída da Maternidade',
 'Conjunto especial para primeira foto e saída da maternidade',
 1,1,'conveniente','OPCIONAL','NO_NASCIMENTO',28,34,0,4,
 false,false,false,true,false,1,
 50,200,12,40,125,26,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['maternidade','roupas','especial'],true,12090),

-- =============================================================
-- PÓS-PARTO (sort 13000+)
-- =============================================================
('pos_parto','Recuperação','Cinta Pós-Parto Abdominal',
 'Cinta de compressão para suporte abdominal na recuperação',
 1,1,'recomendado','IMPORTANTE','NO_NASCIMENTO',32,36,0,26,
 false,false,false,true,false,1,
 80,250,20,60,165,40,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['pós-parto','recuperação'],true,13010),

('pos_parto','Recuperação','Almofada Perineal (rosca)',
 'Almofada em formato de donut para aliviar dor perineal',
 1,1,'essencial','CRITICO','NO_NASCIMENTO',32,36,0,26,
 false,false,false,false,false,1,
 40,120,8,25,80,16,'usa','AGUARDAR_EUA',
 ARRAY['pós-parto','recuperação'],true,13020),

('pos_parto','Recuperação','Spray Calmante Perineal',
 'Spray com hamamelis e lavanda para alívio pós-parto',
 1,2,'recomendado','IMPORTANTE','NO_NASCIMENTO',32,36,0,13,
 false,false,false,false,false,1,
 40,100,8,20,70,14,'usa','AGUARDAR_EUA',
 ARRAY['pós-parto','saúde'],true,13030),

('pos_parto','Recuperação','Pomada para Cuidados Perineais',
 'Pomada cicatrizante e calmante para região perineal',
 1,2,'recomendado','IMPORTANTE','NO_NASCIMENTO',32,36,0,13,
 false,false,false,false,false,1,
 30,80,8,20,55,14,'qualquer','COMPRAR_AGORA_BRASIL',
 ARRAY['pós-parto','saúde'],true,13040),

('pos_parto','Cesárea','Kit Cuidados Cicatriz Cesárea',
 'Micropore, gel de silicone e orientações para cicatriz',
 1,2,'recomendado','IMPORTANTE','NO_NASCIMENTO',32,36,0,26,
 false,false,false,false,false,1,
 30,80,8,20,55,14,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['pós-parto','cesárea'],true,13050),

('pos_parto','Nutrição','Vitaminas Pós-Parto (3 meses)',
 'Suplemento com ferro, ácido fólico e vitaminas para pós-parto',
 1,3,'essencial','CRITICO','NO_NASCIMENTO',28,34,0,26,
 false,false,false,false,false,1,
 60,200,15,50,130,32,'usa','AGUARDAR_EUA',
 ARRAY['pós-parto','nutrição','saúde'],true,13060),

('pos_parto','Monitoramento','Monitor de Pressão Arterial Digital',
 'Monitor de PA para acompanhar pressão no pós-parto imediato',
 1,1,'recomendado','IMPORTANTE','NO_NASCIMENTO',28,34,0,26,
 false,false,true,false,false,1,
 80,250,20,60,165,40,'qualquer','COMPRAR_AGORA_BRASIL',
 ARRAY['pós-parto','saúde','monitoramento'],true,13070),

('pos_parto','Sono','Almofada de Gravidez / Pós-Parto',
 'Almofada em U para suporte durante gestação e amamentação',
 1,1,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,34,0,26,
 true,false,false,true,false,2,
 100,300,25,80,200,52,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['pós-parto','sono','gravidez'],true,13080),

-- =============================================================
-- DOCUMENTOS (sort 14000+)
-- =============================================================
('documentos','Nascimento','Certidão de Nascimento',
 'Registrar no cartório em até 15 dias após o nascimento',
 1,1,'essencial','CRITICO','ATE_3_MESES',32,38,0,208,
 false,false,false,false,false,1,
 0,150,0,0,75,0,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['documentos','legal','obrigatório'],true,14010),

('documentos','Nascimento','CPF do Bebê',
 'Pode ser feito junto com a certidão no cartório',
 1,1,'essencial','CRITICO','ATE_3_MESES',32,38,0,208,
 false,false,false,false,false,1,
 0,0,0,0,0,0,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['documentos','legal','obrigatório'],true,14020),

('documentos','Saúde','Caderneta de Vacinação',
 'Caderneta de vacinação emitida na maternidade',
 1,1,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,208,
 false,false,false,false,false,1,
 0,0,0,0,0,0,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['documentos','saúde','vacinação'],true,14030),

('documentos','Saúde','Caderneta de Saúde da Criança',
 'Caderneta emitida pelo ministério da saúde para acompanhamento',
 1,1,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,208,
 false,false,false,false,false,1,
 0,0,0,0,0,0,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['documentos','saúde'],true,14040),

('documentos','Internacional','Passaporte Infantil Brasileiro',
 'Passaporte para viagens internacionais do bebê',
 1,1,'essencial','CRITICO','ATE_3_MESES',20,38,0,208,
 false,false,false,false,false,1,
 200,300,0,0,250,0,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['documentos','viagem','internacional'],true,14050),

('documentos','Internacional','RNNE (Registro Nascimento no Exterior)',
 'Para bebê nascido no Brasil mas família que vai para o exterior',
 1,1,'essencial','CRITICO','ATE_3_MESES',20,38,0,208,
 false,false,false,false,false,1,
 0,300,0,0,0,0,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['documentos','internacional'],true,14060),

('documentos','Saúde','Declaração de Nascido Vivo (DNV)',
 'Documento emitido pela maternidade — guardar com cuidado',
 1,1,'essencial','CRITICO','NO_NASCIMENTO',20,34,0,208,
 false,false,false,false,false,1,
 0,0,0,0,0,0,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['documentos','legal','essencial'],true,14070),

-- =============================================================
-- MUDANÇA INTERNACIONAL (sort 15000+)
-- =============================================================
('mudanca','Documentos','Passaporte Infantil Americano',
 'Solicitado no consulado americano — processo pode levar semanas',
 1,1,'essencial','CRITICO','ATE_3_MESES',20,38,0,208,
 false,false,false,false,false,1,
 0,0,150,250,0,200,'usa','AGUARDAR_EUA',
 ARRAY['mudança','documentos','eua','essencial'],true,15010),

('mudanca','Documentos','Visto de Dependente (F-2, J-2, H-4)',
 'Visto de dependente conforme status de visto do responsável',
 1,1,'essencial','CRITICO','ATE_3_MESES',20,38,0,208,
 false,false,false,false,false,1,
 0,0,160,220,0,190,'usa','AGUARDAR_EUA',
 ARRAY['mudança','documentos','visto'],true,15020),

('mudanca','Documentos','Apostila de Haia na Certidão de Nascimento',
 'Apostila internacional na certidão para uso no exterior',
 1,1,'essencial','CRITICO','ATE_3_MESES',20,38,0,208,
 false,false,false,false,false,1,
 50,200,0,0,125,0,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['mudança','documentos','legal'],true,15030),

('mudanca','Documentos','Certidão de Nascimento Traduzida',
 'Tradução juramentada da certidão para inglês',
 1,1,'essencial','CRITICO','ATE_3_MESES',20,38,0,208,
 false,false,false,false,false,1,
 200,500,0,0,350,0,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['mudança','documentos','tradução'],true,15040),

('mudanca','Saúde','Comprovante Internacional de Vacinação',
 'Cartela amarela de vacinação internacional (caderneta ANVISA)',
 1,1,'essencial','CRITICO','ATE_3_MESES',20,38,0,208,
 false,false,false,false,false,1,
 0,30,0,0,0,0,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['mudança','saúde','vacinação'],true,15050),

('mudanca','Saúde','Seguro Saúde Internacional (Família)',
 'Plano de saúde para o período de transição nos EUA',
 1,1,'essencial','CRITICO','NO_NASCIMENTO',20,38,0,208,
 false,false,false,false,false,1,
 800,3000,100,600,1900,350,'usa','AGUARDAR_EUA',
 ARRAY['mudança','saúde','seguro'],true,15060),

('mudanca','Saúde','Pediatra nos EUA (pesquisa e marcação)',
 'Pesquisar e marcar pediatra antes da chegada nos EUA',
 1,1,'essencial','CRITICO','NO_NASCIMENTO',20,38,0,208,
 false,false,false,false,false,1,
 0,0,150,400,0,275,'usa','AGUARDAR_EUA',
 ARRAY['mudança','saúde','eua'],true,15070),

('mudanca','Viagem','Kit de Emergência para Voo com Bebê',
 'Fraldas extras, roupas de reserva, lenços, snacks para amamentação',
 1,1,'essencial','CRITICO','NO_NASCIMENTO',20,38,0,208,
 false,false,false,false,false,1,
 50,150,10,30,100,20,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['mudança','viagem','avião'],true,15080),

('mudanca','Elétrico','Adaptador de Tomadas EUA (kit 3)',
 'Adaptadores para tomadas americanas (tipo A/B)',
 1,2,'essencial','CRITICO','NO_NASCIMENTO',20,38,0,208,
 false,false,false,false,false,1,
 20,60,5,15,40,10,'brasil','COMPRAR_AGORA_BRASIL',
 ARRAY['mudança','elétrico','eua'],true,15090),

('mudanca','Elétrico','Carregador Portátil (Power Bank)',
 'Bateria externa para longas viagens e apagões',
 1,1,'recomendado','IMPORTANTE','NO_NASCIMENTO',20,38,0,208,
 false,false,true,true,false,1,
 80,250,20,60,165,40,'usa','AGUARDAR_EUA',
 ARRAY['mudança','viagem'],true,15100),

('mudanca','Instalação','Baby Proofing nos EUA (kit)',
 'Travas, proteções de tomada e cancelas para a nova casa',
 1,1,'recomendado','IMPORTANTE','ATE_3_MESES',20,38,0,208,
 false,false,true,false,true,3,
 0,0,50,150,0,100,'usa','AGUARDAR_EUA',
 ARRAY['mudança','segurança','eua'],true,15110),

('mudanca','Instalação','Babá nos EUA (pesquisa e entrevistas)',
 'Contratação de babá ou daycare na cidade de destino',
 1,1,'recomendado','IMPORTANTE','ATE_3_MESES',20,38,0,208,
 false,false,true,false,false,1,
 0,0,0,0,0,0,'usa','AGUARDAR_EUA',
 ARRAY['mudança','cuidador','eua'],true,15120),

('mudanca','Financeiro','Conta Bancária nos EUA',
 'Abrir conta antes da chegada — Wise, Mercury, ou banco local',
 1,1,'essencial','CRITICO','NO_NASCIMENTO',20,38,0,208,
 false,false,false,false,false,1,
 0,0,0,0,0,0,'usa','AGUARDAR_EUA',
 ARRAY['mudança','financeiro','eua'],true,15130),

('mudanca','Compras EUA','Berço para os EUA',
 'Berço adequado às normas ASTM americanas — comprar no destino',
 1,1,'essencial','CRITICO','ATE_3_MESES',20,38,0,104,
 false,true,true,true,true,10,
 0,0,150,500,0,325,'usa','AGUARDAR_EUA',
 ARRAY['mudança','quarto','eua'],true,15140),

('mudanca','Compras EUA','Car Seat para os EUA',
 'Cadeirinha de carro certificada NHTSA — obrigatória nos EUA',
 1,1,'essencial','CRITICO','NO_NASCIMENTO',20,38,0,52,
 false,true,true,true,false,4,
 0,0,100,350,0,225,'usa','AGUARDAR_EUA',
 ARRAY['mudança','carro','eua','obrigatório'],true,15150)

ON CONFLICT (item_name, category) DO UPDATE SET
  subcategory    = EXCLUDED.subcategory,
  description    = EXCLUDED.description,
  ideal_quantity = EXCLUDED.ideal_quantity,
  max_quantity   = EXCLUDED.max_quantity,
  need_level     = EXCLUDED.need_level,
  criticality    = EXCLUDED.criticality,
  usage_period   = EXCLUDED.usage_period,
  buy_week_from  = EXCLUDED.buy_week_from,
  buy_week_to    = EXCLUDED.buy_week_to,
  use_from_week  = EXCLUDED.use_from_week,
  use_to_week    = EXCLUDED.use_to_week,
  can_borrow     = EXCLUDED.can_borrow,
  can_rent       = EXCLUDED.can_rent,
  can_wait       = EXCLUDED.can_wait,
  good_as_gift   = EXCLUDED.good_as_gift,
  is_large_item  = EXCLUDED.is_large_item,
  weight_kg      = EXCLUDED.weight_kg,
  price_brl_min  = EXCLUDED.price_brl_min,
  price_brl_max  = EXCLUDED.price_brl_max,
  price_usd_min  = EXCLUDED.price_usd_min,
  price_usd_max  = EXCLUDED.price_usd_max,
  avg_price_brl  = EXCLUDED.avg_price_brl,
  avg_price_usd  = EXCLUDED.avg_price_usd,
  country_rec    = EXCLUDED.country_rec,
  base_recommendation = EXCLUDED.base_recommendation,
  tags           = EXCLUDED.tags,
  sort_order     = EXCLUDED.sort_order,
  updated_at     = now();
